checks:
    php: true

filter:
    paths:
        - "src/*"
    dependency_paths:
        - "vendor/*"
    excluded_paths:
        - "vendor/*"

tools:
    php_analyzer: true
    php_changetracking: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
    php_cpd: true
    php_mess_detector: true
    php_pdepend: true
    php_sim: true

build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'clover'